"""Pre-build step: gzip the web UI into a C array.

The config page is by far the largest object in the firmware — 47 KB of HTML,
CSS and JS, bigger than the entire mining core — and it lived in flash
uncompressed. Browsers have understood Content-Encoding: gzip since forever, so
storing it compressed costs nothing at runtime beyond the header and buys back
about 32 KB of the OTA slot.

Runs automatically from platformio.ini (extra_scripts). The generated header is
build output, not source, so it is gitignored and regenerated every build.
"""
import gzip
import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

# PlatformIO execs this through SCons, where __file__ is not defined; the
# project directory comes from the injected environment instead.
ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
SRC = os.path.join(ROOT, "src", "webui.html")
OUT = os.path.join(ROOT, "src", "webui_gz.h")


def generate():
    with open(SRC, "rb") as f:
        raw = f.read()
    # mtime=0 so the output is byte-identical for identical input, which keeps
    # incremental builds from relinking on every run.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = [
        "// Generated by tools/gen_webui.py from src/webui.html — do not edit.",
        "// Served with Content-Encoding: gzip; see WebPortal.cpp.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"// {len(raw)} bytes of HTML -> {len(packed)} bytes gzipped",
        f"#define WEBUI_GZ_LEN {len(packed)}",
        "static const uint8_t WEBUI_GZ[] PROGMEM = {",
    ]
    for i in range(0, len(packed), 16):
        chunk = packed[i:i + 16]
        lines.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    body = "\n".join(lines) + "\n"

    # Only rewrite when it actually changes, so the build does not churn.
    if os.path.exists(OUT):
        with open(OUT, "r") as f:
            if f.read() == body:
                return len(raw), len(packed)
    with open(OUT, "w") as f:
        f.write(body)
    return len(raw), len(packed)


raw_len, gz_len = generate()
print(f"webui: {raw_len} bytes -> {gz_len} gzipped (saved {raw_len - gz_len} bytes of flash)")
