#!/usr/bin/env python3
"""Rasterise a TTF subset into an Adafruit-GFX font header for the clock.

The clock's "Sans" face is real type, not the scaled 5x7 bitmap — but only
eleven glyphs of it ('0'..'9' and ':'), because a full font at clock size
would be tens of KB and the clock never prints a letter with it. The digits
are forced monospaced (every digit gets the widest digit's advance) so the
time does not shuffle sideways as the minutes tick over; the colon keeps its
own narrower advance.

Output is checked before it is written: every glyph's bitmap is unpacked
again from the emitted bytes and compared with what Pillow rendered, so a
packing bug fails this script instead of drawing garbage on the panel.

Needs Pillow. Regenerate with:  python3 tools/gen_font.py
"""
from PIL import Image, ImageFont, ImageDraw
from pathlib import Path

TTF = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
SIZE_PT = 76                     # ~54 px tall digits on the 240px panel
CHARS = "0123456789:"            # 0x30..0x3A — contiguous, as GFXfont requires
OUT = Path("src/features/clock/font_clock_sans.h")
NAME = "ClockSans"


def render_glyph(font, ch):
    """Tight 1-bit bitmap plus metrics, Pillow's baseline convention."""
    # Draw on a generous canvas, then crop to the ink.
    W = H = SIZE_PT * 3
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    origin = (SIZE_PT, SIZE_PT * 2)      # pen position = glyph origin
    # anchor="ls": the origin is the BASELINE, matching the GFXfont convention.
    # Pillow's default anchors at the ascender, which flips every yOffset's
    # sign and draws the whole face one line low.
    d.text(origin, ch, font=font, fill=255, anchor="ls")
    bbox = img.getbbox()
    if bbox is None:                     # blank glyph (not expected in this set)
        return [], 0, 0, 0, 0
    x0, y0, x1, y1 = bbox
    img = img.crop(bbox).point(lambda v: 255 if v >= 128 else 0)
    w, h = img.size
    rows = [[1 if img.getpixel((x, y)) else 0 for x in range(w)] for y in range(h)]
    x_off = x0 - origin[0]
    y_off = y0 - origin[1]               # negative: ink starts above the baseline
    return rows, w, h, x_off, y_off


def pack(rows, w, h):
    """GFXfont bitmap: rows concatenated, MSB first, no per-row padding."""
    bits = [px for row in rows for px in row]
    out = []
    for i in range(0, len(bits), 8):
        b = 0
        for j, px in enumerate(bits[i:i + 8]):
            if px:
                b |= 0x80 >> j
        out.append(b)
    return out


def unpack(data, w, h):
    """Inverse of pack(), for the self-check."""
    bits = []
    for b in data:
        for j in range(8):
            bits.append(1 if b & (0x80 >> j) else 0)
    return [bits[y * w:(y + 1) * w] for y in range(h)]


def main():
    font = ImageFont.truetype(TTF, SIZE_PT)
    glyphs = []
    for ch in CHARS:
        rows, w, h, xo, yo = render_glyph(font, ch)
        adv = font.getlength(ch)
        glyphs.append({"ch": ch, "rows": rows, "w": w, "h": h,
                       "xo": xo, "yo": yo, "adv": round(adv)})

    # Monospace the digits on the widest one; centre each within that advance.
    digit_adv = max(g["adv"] for g in glyphs if g["ch"].isdigit())
    for g in glyphs:
        if g["ch"].isdigit():
            g["xo"] += (digit_adv - g["adv"]) // 2
            g["adv"] = digit_adv

    bitmap, entries = [], []
    for g in glyphs:
        data = pack(g["rows"], g["w"], g["h"])
        if unpack(data, g["w"], g["h"]) != [r[:] for r in g["rows"]]:
            raise SystemExit(f"glyph '{g['ch']}' does not survive the round trip")
        entries.append((len(bitmap), g))
        bitmap.extend(data)

    ascent = max(-g["yo"] for g in glyphs)
    descent = max(g["yo"] + g["h"] for g in glyphs)

    lines = [
        "// font_clock_sans.h - GENERATED by tools/gen_font.py. Do not edit by hand.",
        f"// {Path(TTF).name} at {SIZE_PT}pt, glyphs '{CHARS}' only, digits monospaced.",
        f"// {len(bitmap)} bytes of bitmap. Ascent {ascent}px, descent {descent}px.",
        "#pragma once",
        "#include <Arduino_GFX_Library.h>   // GFXfont / GFXglyph",
        "",
        f"#define CLOCK_SANS_ASCENT  {ascent}",
        f"#define CLOCK_SANS_DESCENT {descent}",
        f"#define CLOCK_SANS_DIGIT_ADV {digit_adv}",
        f"#define CLOCK_SANS_COLON_ADV {next(g['adv'] for g in glyphs if g['ch'] == ':')}",
        "",
        f"static const uint8_t {NAME}Bitmaps[] PROGMEM = {{",
    ]
    for i in range(0, len(bitmap), 16):
        lines.append("  " + "".join(f"0x{b:02X}," for b in bitmap[i:i + 16]))
    lines += ["};", "", f"static const GFXglyph {NAME}Glyphs[] PROGMEM = {{"]
    for off, g in entries:
        lines.append(
            f"  {{{off:5d}, {g['w']:3d}, {g['h']:3d}, {g['adv']:3d}, "
            f"{g['xo']:3d}, {g['yo']:4d}}},   // '{g['ch']}'")
    lines += [
        "};",
        "",
        f"static const GFXfont {NAME} PROGMEM = {{",
        f"  (uint8_t*){NAME}Bitmaps, (GFXglyph*){NAME}Glyphs,",
        f"  0x{ord(CHARS[0]):02X}, 0x{ord(CHARS[-1]):02X}, {ascent + descent + 6}}};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {len(bitmap)} bytes of bitmap, "
          f"ascent {ascent}, digit advance {digit_adv}")


if __name__ == "__main__":
    main()
