// TextFold.h — fold UTF-8 into the ASCII the panel fonts can draw.
//
// Calendar titles and Spotify names arrive as UTF-8. The panel fonts are
// ASCII (the classic font's high half is CP437), so drawing the raw bytes
// turns a curly apostrophe (U+2019, three bytes) into three accented glyphs:
// "Doctor's" became "DoctorÇǔs" on a real screen. Every string from outside
// runs through this fold as it is stored: typographic punctuation becomes its
// ASCII cousin, Latin-1 letters lose their accents, and anything else
// multi-byte is dropped rather than mojibake'd.
//
// In-place and never longer than the input (every mapping is at most as many
// bytes as the sequence it replaces). No Arduino dependencies: the ICS parser
// includes this on the host, where the self-test feeds it real event titles.
#pragma once
#include <stdint.h>
#include <stddef.h>

// Latin-1 Supplement letters 0xC0..0xFF folded to their base letter. The two
// non-letters in the run (× 0xD7, ÷ 0xF7) fold to a space and are dropped by
// the caller loop below writing ' '.
static const char kLatin1Fold[64] = {
  'A','A','A','A','A','A','A','C','E','E','E','E','I','I','I','I',
  'D','N','O','O','O','O','O',' ','O','U','U','U','U','Y','T','s',
  'a','a','a','a','a','a','a','c','e','e','e','e','i','i','i','i',
  'd','n','o','o','o','o','o',' ','o','u','u','u','u','y','t','y',
};

// Latin Extended-A 0x100..0x17F folded to base letters. Generated by NFD
// decomposition (plus the stroked/ligature letters NFD leaves alone: Đ Ħ ı
// ĸ Ł Ŋ Œ Ŧ ſ); a space marks "no clean base — drop". Do not hand-edit;
// the self-test re-derives spot values.
static const char kLatinExtFold[128 + 1] =
    "AaAaAaCcCcCcCcDdDdEeEeEeEeEeGgGgGgGgHhHhIiIiIiIiIi  JjKkkLlLlLl "
    " LlNnNnNn NnOoOoOoOoRrRrRrSsSsSsSsTtTtTtUuUuUuUuUuUuWwYyYZzZzZzs";

// Fold one code point into `out` (ASCII, NUL-terminated). Empty result means
// the code point has no sensible ASCII cousin and is dropped.
static inline void textFoldCp(uint32_t cp, char out[4]) {
  out[0] = 0;
  switch (cp) {
    case 0x2018: case 0x2019: case 0x201A: case 0x02BC:
      out[0] = '\''; out[1] = 0; return;
    case 0x201C: case 0x201D: case 0x201E:
      out[0] = '"'; out[1] = 0; return;
    case 0x2013: case 0x2014: case 0x2015: case 0x2212:
    case 0x2022: case 0x00B7:
      out[0] = '-'; out[1] = 0; return;
    case 0x2026:
      out[0] = out[1] = out[2] = '.'; out[3] = 0; return;
    case 0x00A0:
      out[0] = ' '; out[1] = 0; return;
    default: break;
  }
  char c = 0;
  if (cp >= 0xC0 && cp <= 0xFF)        c = kLatin1Fold[cp - 0xC0];
  else if (cp >= 0x100 && cp <= 0x17F) c = kLatinExtFold[cp - 0x100];
  if (c && c != ' ') { out[0] = c; out[1] = 0; }
}

// Fold a UTF-8 string to ASCII in place. Bytes < 0x80 pass through; valid
// multi-byte sequences fold via textFoldCp; stray or truncated sequences are
// dropped. The result is always a valid C string no longer than the input.
static inline void textFoldUtf8(char* s) {
  if (!s) return;
  const unsigned char* r = (const unsigned char*)s;
  char* w = s;
  while (*r) {
    unsigned char b = *r;
    if (b < 0x80) { *w++ = (char)b; r++; continue; }
    // Decode one UTF-8 sequence (2..4 bytes).
    uint32_t cp = 0;
    int len = 0;
    if      ((b & 0xE0) == 0xC0) { cp = b & 0x1F; len = 2; }
    else if ((b & 0xF0) == 0xE0) { cp = b & 0x0F; len = 3; }
    else if ((b & 0xF8) == 0xF0) { cp = b & 0x07; len = 4; }
    else { r++; continue; }                 // stray continuation byte: drop
    int ok = 1;
    for (int i = 1; i < len; i++) {
      if ((r[i] & 0xC0) != 0x80) { ok = 0; break; }
      cp = (cp << 6) | (r[i] & 0x3F);
    }
    if (!ok) { r++; continue; }             // truncated sequence: drop the lead
    r += len;
    char folded[4];
    textFoldCp(cp, folded);
    for (const char* f = folded; *f; f++) *w++ = *f;
  }
  *w = 0;
}
